/* Plugin Template generated by Pawn Studio */

#include <sourcemod>
#include "W3SIncs/War3Source_Interface"

new thisRaceID;

public Plugin:myinfo = 
{
	name = "War3Source Random Race",
	author = "Necavi",
	description = "The Random race for War3Source.",
	version = "1.1",
	url = "http://www.necavi.org/"
};

public OnWar3LoadRaceOrItemOrdered(num)
{
	if(num==1)
	{
		thisRaceID=War3_CreateNewRace("A Random Race","rand");
		War3_CreateRaceEnd(thisRaceID);
		RegConsoleCmd("sm_rand", Command_Rand)
	}
}

public OnRaceChanged(client,oldrace,newrace)
{
	if(newrace==thisRaceID){
		Execute_Rand(client);
	}
}

public Action:Command_Rand(client, args)
{
	if(ValidPlayer(client)!=ValidPlayer(client,true))
	{
		Execute_Rand(client);
	} else {
		War3_ChatMessage(client,"You are only able to change race when you are dead, please complain to necavi if you want him to add a queue.");
	}
}

Execute_Rand(client)
{
	new race = GetRandomInt(1,War3_GetRacesLoaded());
	while(!CanSelectRace(client,race)){
		race = GetRandomInt(1,War3_GetRacesLoaded());
	}
	War3_SetRace(client,race);
}










